package oop;

import static oop.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Febrianatha
 */
public class keuangan extends javax.swing.JFrame {
     DefaultTableModel DTM = new DefaultTableModel();

    
     private void loadDataFromDatabase() {
    try {
        Connection c = koneksi();
        String sql = "SELECT * FROM transaksi";
        PreparedStatement p = c.prepareStatement(sql);
        ResultSet r = p.executeQuery();

        DTM.setRowCount(0); // clear tabel
        while(r.next()) {
            DTM.addRow(new Object[]{
                r.getString("ID_TRANSAKSI"),
                r.getString("TANGGAL"),
                r.getString("JENIS_TRANSAKSI"),
                r.getDouble("NOMINAL"),
                r.getString("KETERANGAN")
            });
        }
        r.close();
        p.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}

    public keuangan() {
        initComponents();
        
        tbltransaksi.setModel(DTM);
        DTM.addColumn("ID_TRANSAKSI");
        DTM.addColumn("TANGGAL");
        DTM.addColumn("JENIS_TRANSAKSI");
        DTM.addColumn("NOMINAL");
        DTM.addColumn("KETERANGAN");
        
        // ==== Mouse Listener agar klik tabel muncul di input ====
    tbltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tbltransaksi.getSelectedRow();
            if(row >= 0){
                txID.setText(tbltransaksi.getValueAt(row, 0).toString());
                txTGL.setText(tbltransaksi.getValueAt(row, 1).toString());
                txTRANSAKSI.setSelectedItem(tbltransaksi.getValueAt(row, 2).toString());
                txNOMINAL.setText(tbltransaksi.getValueAt(row, 3).toString());
                txKET.setText(tbltransaksi.getValueAt(row, 4).toString());
            }
        }
    });
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cBARU = new javax.swing.JButton();
        cHAPUS = new javax.swing.JButton();
        cUBAH = new javax.swing.JButton();
        cTUTUP = new javax.swing.JButton();
        txID = new javax.swing.JTextField();
        txTGL = new javax.swing.JTextField();
        txNOMINAL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txKET = new javax.swing.JTextField();
        txTRANSAKSI = new javax.swing.JComboBox<>();

        jLabel2.setText("ID_Transaksi");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA KEUANGAN BULANAN");

        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Jenis Transaksi", "Nominal", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tbltransaksi);

        jLabel8.setText("ID_TRANSAKSI");

        jLabel9.setText("TANGGAL");

        jLabel10.setText("JENIS_TRANSAKSI");

        jLabel11.setText("NOMINAL");

        cBARU.setText("Baru");
        cBARU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBARUActionPerformed(evt);
            }
        });

        cHAPUS.setText("Hapus");
        cHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHAPUSActionPerformed(evt);
            }
        });

        cUBAH.setText("Ubah");
        cUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUBAHActionPerformed(evt);
            }
        });

        cTUTUP.setText("Tutup");
        cTUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTUTUPActionPerformed(evt);
            }
        });

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txTGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTGLActionPerformed(evt);
            }
        });

        jLabel12.setText("KETERANGAN");

        txTRANSAKSI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));
        txTRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTRANSAKSIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBARU)
                                .addGap(36, 36, 36)
                                .addComponent(cUBAH)
                                .addGap(29, 29, 29)
                                .addComponent(cHAPUS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(cTUTUP))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(txID)
                                    .addComponent(jLabel8)
                                    .addComponent(txTGL)
                                    .addComponent(txNOMINAL)
                                    .addComponent(jLabel12)
                                    .addComponent(txKET, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(txTRANSAKSI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTRANSAKSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNOMINAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKET, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBARU)
                            .addComponent(cUBAH)
                            .addComponent(cHAPUS)
                            .addComponent(cTUTUP))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cBARUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBARUActionPerformed
        String ID_TRANSAKSI = txID.getText();
        String TANGGAL = txTGL.getText();
        String JENIS_TRANSAKSI = txTRANSAKSI.getSelectedItem().toString();
        String NOMINAL = txNOMINAL.getText();
        String KETERANGAN = txKET.getText();

    // Validasi sederhana agar data tidak kosong
    if(ID_TRANSAKSI.isEmpty() || TANGGAL.isEmpty() || JENIS_TRANSAKSI.isEmpty() || NOMINAL.isEmpty()){
        JOptionPane.showMessageDialog(this, "Mohon isi semua data (ID, Tanggal, Jenis, Nominal)!");
        return;
    }
     try {
        Connection c = koneksi();
        String sql = "INSERT INTO transaksi VALUES (?, ?, ?, ?, ?)";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, ID_TRANSAKSI);
        p.setString(2, TANGGAL);
        p.setString(3, JENIS_TRANSAKSI);
        p.setDouble(4, Double.parseDouble(NOMINAL));
        p.setString(5, KETERANGAN);
        p.executeUpdate();
        p.close();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
    }
    
    // refresh tabel
    loadDataFromDatabase();

  
    // Clear input setelah tambah data
    txID.setText("");
    txTGL.setText("");
    txTRANSAKSI.setSelectedIndex(0);
    txNOMINAL.setText("");
    txKET.setText("");

    // Fokus ke ID lagi agar user bisa input data berikutnya
    txID.requestFocus();
    
    }//GEN-LAST:event_cBARUActionPerformed

    private void cHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHAPUSActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbltransaksi.getSelectedRow();
        if(selectedRow >= 0){
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Apakah Anda yakin ingin menghapus data ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
            String id = tbltransaksi.getValueAt(selectedRow, 0).toString();
            try {
                Connection c = koneksi();
                String sql = "DELETE FROM transaksi WHERE ID_TRANSAKSI=?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }

            loadDataFromDatabase();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
    }

    }//GEN-LAST:event_cHAPUSActionPerformed

    private void cTUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTUTUPActionPerformed
        // TODO add your handling code here:
            dispose(); // menutup jendela
     
    }//GEN-LAST:event_cTUTUPActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void txTGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTGLActionPerformed

    private void cUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUBAHActionPerformed
        // TODO add your handling code here:
     int selectedRow = tbltransaksi.getSelectedRow();
    if(selectedRow >= 0){
        String ID_TRANSAKSI = txID.getText();
        String TANGGAL = txTGL.getText();
        
        String NOMINAL = txNOMINAL.getText();
        String KETERANGAN = txKET.getText();

        try {
            Connection c = koneksi();
            String sql = "UPDATE transaksi SET TANGGAL=?, JENIS_TRANSAKSI=?, NOMINAL=?, KETERANGAN=? WHERE ID_TRANSAKSI=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, TANGGAL);
            String JENIS_TRANSAKSI = txTRANSAKSI.getSelectedItem().toString();
            p.setString(2, JENIS_TRANSAKSI);
            p.setDouble(3, Double.parseDouble(NOMINAL));
            p.setString(4, KETERANGAN);
            p.setString(5, ID_TRANSAKSI);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }

        loadDataFromDatabase();

        // clear
        txID.setText("");
        txTGL.setText("");
        txTRANSAKSI.setSelectedIndex(0);
        txNOMINAL.setText("");
        txKET.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Pilih dulu data yang mau diubah!");
        }
    }//GEN-LAST:event_cUBAHActionPerformed

    private void txTRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTRANSAKSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                 javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(keuangan.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new keuangan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBARU;
    private javax.swing.JButton cHAPUS;
    private javax.swing.JButton cTUTUP;
    private javax.swing.JButton cUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltransaksi;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txKET;
    private javax.swing.JTextField txNOMINAL;
    private javax.swing.JTextField txTGL;
    private javax.swing.JComboBox<String> txTRANSAKSI;
    // End of variables declaration//GEN-END:variables

}